### ISSUE TITLE
"students" Global variable syntax

### ISSUE THREAD

**Issue by rkclark** [makersacademy/student-directory#17]
Hey

In part 10 "Refactoring the Code" we create a global variable to hold the students array. 

The tutorial names the variable `@students`, but my understanding is that global variables in Ruby are pre-fixed with a `$`, so should it not be `$students` instead? From what I have learnt the `@` denotes instance variables which we would use if we were creating instance variables in a class.

Am I misunderstanding the status of this variable - is it not global?

Cheers

Rick

**Comment by dylanrhodius** [comment]
Hey! Haven't reached that ex yet but as far as I know:
@ and self. : instance variables 
@@ : class variables 
$ : global variables 

So I would think the same as you. I know that's half the answer you are looking for Rick, maybe someone else can complete it with a short explanation on variables?

**Comment by JamesTurnerGit** [comment]
I think since you originally declare `@students` in the main part of your code...
and your whole program is an object/class...
it's a object variable for your whole program?

I think it might be a style thing to prefer `$`'s as there's less room for confusion about the true scope of a variable. It could also be that $'s came later on in the lifespan of the language and this material was written in the old style? either way both seem to work.

>It's actually very tricky to google this properly so this is inferred/may be more wrong than usual!
